name: darea
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio>2.3
  - pytorch
  - git-lfs
  - torchaudio
  - pysoundfile
  - pytest 
  - numpy
  - ffmpeg<7
  - speex
