name: darea
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio>2.3
  - pytorch
  - git-lfs
  - transformers
  - torchaudio
  - pysoundfile
  - pytest 
  - numpy
  - ffmpeg<7
  - speex
  - pip:
    - descript-audio-codec
    - git+https://github.com/ollipauna/encodec.git@main
    - git+https://github.com/ollipauna/speechtokenizer.git@main
    - git+https://github.com/ollipauna/moshi.git@main
    - beartype
  